CREATE OR REPLACE PROCEDURE CHECK_AGE_ELIGIBILITY(
V_ID IN EMPLOYEE.EMPID%TYPE,
V_NAME IN EMPLOYEE.EMPNAME%TYPE, 
V_AGE IN EMPLOYEE.AGE%TYPE)
IS

BEGIN 
CASE WHEN (V_AGE>=18)
THEN INSERT INTO EMPLOYEE VALUES(V_ID, V_NAME, V_AGE);
DBMS_OUTPUT.PUT_LINE('Age valid - Record inserted');
WHEN (V_AGE<18)
THEN DBMS_OUTPUT.PUT_LINE('Age invalid - Record not inserted');
END CASE;

END;
/