CREATE OR REPLACE PROCEDURE SELECT_INVOICE(INVOICE_ID IN NUMBER, INVOICE_DETAILS OUT SYS_REFCURSOR)
AS

BEGIN
OPEN INVOICE_DETAILS FOR
SELECT STATUS, PAPER_INVOICE_BATCH_NUMBER FROM INVOICE I WHERE INVOICE_ID= I.ID;

END;
/